import type {
  AudienceCard,
  LandingCta,
  Restaurant,
  StoreCategory,
} from "@/types/YemekYol";

const img = (file: string) =>
  `/sites/YemekYol-com-bb18bd46/root-8a5edab2/images/${file}`;

export const audienceCards: AudienceCard[] = [
  {
    title: "Become a Dasher",
    body: "As a delivery driver, make money and work on your schedule. Sign up in minutes.",
    action: "Start earning",
    image: img("scoot-scoot.svg"),
    imageAlt: "Become a Dasher",
  },
  {
    title: "Become a Merchant",
    body: "Attract new customers and grow sales, starting with 0% commissions for up to 30 days.",
    action: "Sign up for YemekYol",
    image: img("storefront.svg"),
    imageAlt: "Become a Merchant",
  },
  {
    title: "Get the best YemekYol experience",
    body: "Experience the best your neighborhood has to offer, all in one app.",
    action: "Get the app",
    image: img("iphone.svg"),
    imageAlt: "Get the best YemekYol experience",
  },
];

export const landingCtas: LandingCta[] = [
  {
    title: "Everything you crave, delivered.",
    eyebrow: "Your favorite local restaurants",
    body: "Get a slice of pizza or the whole pie delivered, or pick up house lo mein from the Chinese takeout spot you've been meaning to try.",
    action: "Find restaurants",
    image: img("download-the-app.png"),
    imageAlt: "Everything you crave, delivered.",
  },
  {
    title: "DashPass is delivery for less",
    body: "Members get a $0 delivery fee on DashPass orders, 5% back on pickup orders, and so much more. Plus, it's free for 30 days.",
    action: "Get DashPass",
    image: img("dashpass.png"),
    imageAlt: "DashPass is delivery for less",
    imageFirst: true,
  },
  {
    title: "Get grocery and convenience store essentials",
    eyebrow: "Grocery delivery, exactly how you want it.",
    body: "Shop from home and fill your cart with fresh produce, frozen entrees, deli delights and more.",
    action: "Shop Groceries",
    image: img("grocery.png"),
    imageAlt: "Get grocery and convenience store essentials",
  },
  {
    title: "Convenience stores at your doorstep",
    body: "Stock up on snacks, household essentials, candy, or vitamins — all delivered in under an hour.",
    action: "Shop Now",
    image: img("convenience.png"),
    imageAlt: "Convenience stores at your doorstep",
    imageFirst: true,
  },
  {
    title: "Beauty essentials from top brands",
    eyebrow: "Helping you with to-dos and gifting",
    body: "Get all your beauty and self-care needs delivered at home or on-the-go",
    action: "Shop beauty",
    image: img("beauty.png"),
    imageAlt: "Beauty essentials from top brands",
  },
  {
    title: "Flowers for any occasion",
    body: "Shop hand-picked and thoughtfully-arranged blooms from florists near you.",
    action: "Send Flowers",
    image: img("flowers.png"),
    imageAlt: "Flowers for any occasion",
    imageFirst: true,
  },
  {
    title: "Restock the minibar",
    body: "Hosting a get-together or need or need a special cocktail ingredient? Get liquor, beer, mixers, champagne and wine delivered fast.*",
    action: "Shop Alcohol",
    image: img("alcohol.png"),
    imageAlt: "Restock the minibar",
    footnote: "*Must be 21+. Enjoy responsibly.",
  },
  {
    title: "What your pets need, and want",
    body: "Finally, something cat people and dog people agree on — pet supplies delivery. Shop pet food, chew toys, and even costumes.",
    action: "Get Pet Supplies",
    image: img("pet-supplies.png"),
    imageAlt: "What your pets need, and want",
    imageFirst: true,
  },
  {
    title: "Sign up to dash and get paid",
    eyebrow: "Unlocking opportunity for Dashers and businesses",
    body: "Deliver with the #1 Food and Drink App in the U.S. As a delivery driver, you'll make money and work on your schedule. Sign up in minutes.",
    action: "Become a Dasher",
    image: img("become-a-dasher.png"),
    imageAlt: "Sign up to dash and get paid",
  },
  {
    title: "Grow your business with YemekYol",
    body: "Businesses large and small partner with YemekYol to reach new customers, increase order volume, and drive more sales.",
    action: "Become a Partner",
    image: img("work-with-YemekYol.png"),
    imageAlt: "Grow your business with YemekYol",
    imageFirst: true,
  },
];

export const topCities = [
  "New York",
  "Los Angeles",
  "Toronto",
  "Chicago",
  "Houston",
  "Brooklyn",
  "San Diego",
  "Las Vegas",
  "San Francisco",
  "Seattle",
  "Atlanta",
  "Queens",
  "Vancouver, BC",
  "Miami",
  "San Antonio",
];

export const topCuisines = [
  "Pizza",
  "Chinese Food",
  "Sushi",
  "Cafe",
  "Thai Food",
  "Lunch",
  "Seafood",
  "Indian Food",
  "Dessert",
  "Burgers",
  "Asian Food",
  "Italian Food",
  "Vegan Food",
  "Sandwiches",
  "Restaurants",
];

export const topChains = [
  "Target",
  "Panda Express",
  "Dunkin'",
  "Wingstop",
  "Wendy's",
  "Popeyes Louisiana Kitchen",
  "Burger King",
  "Subway",
  "Chick-fil-A",
  "Taco Bell",
  "McDonald's",
  "Dollar General",
  "Chipotle Mexican Grill",
  "7-Eleven",
  "Starbucks",
];

export const popularCategories = [
  "Alcohol Delivery",
  "Beauty Stores",
  "Catering Near Me",
  "DashMart Near Me",
  "Flower Delivery",
  "Grocery Delivery",
  "Medicine Delivery",
  "Pet Store Near Me",
  "Retail Stores Near Me",
  "Reserve a Table",
  "Convenience Stores",
  "Halloween",
];

export const storeCategories: StoreCategory[] = [
  { id: "all", label: "All" },
  { id: "grocery", label: "Grocery" },
  { id: "convenience", label: "Convenience" },
  { id: "alcohol", label: "Alcohol" },
  { id: "pets", label: "Pets" },
  { id: "offers", label: "Offers" },
  { id: "pickup", label: "Pickup" },
  { id: "pizza", label: "Pizza" },
  { id: "sushi", label: "Sushi" },
  { id: "burgers", label: "Burgers" },
  { id: "mexican", label: "Mexican" },
  { id: "asian", label: "Asian" },
  { id: "healthy", label: "Healthy" },
  { id: "dessert", label: "Dessert" },
  { id: "coffee", label: "Coffee" },
];

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Golden Gate Burgers",
    image: img("restaurant-burger.jpg"),
    cuisine: "Burgers • American",
    rating: 4.8,
    ratingsCount: "(2,104)",
    eta: "22 min",
    fee: "$0 delivery fee",
    distance: "0.8 mi",
    dashpass: true,
    promo: "$0 delivery fee on first order",
    categoryIds: ["all", "burgers", "offers"],
  },
  {
    id: "2",
    name: "North Beach Pizzeria",
    image: img("restaurant-pizza.jpg"),
    cuisine: "Pizza • Italian",
    rating: 4.7,
    ratingsCount: "(3,891)",
    eta: "28 min",
    fee: "$1.99 delivery fee",
    distance: "1.2 mi",
    dashpass: true,
    categoryIds: ["all", "pizza"],
  },
  {
    id: "3",
    name: "Sakura Sushi Bar",
    image: img("restaurant-sushi.jpg"),
    cuisine: "Sushi • Japanese",
    rating: 4.9,
    ratingsCount: "(1,540)",
    eta: "35 min",
    fee: "$0 delivery fee",
    distance: "1.6 mi",
    dashpass: true,
    categoryIds: ["all", "sushi", "asian", "offers"],
  },
  {
    id: "4",
    name: "Mission Street Tacos",
    image: img("restaurant-tacos.jpg"),
    cuisine: "Mexican • Tacos",
    rating: 4.6,
    ratingsCount: "(4,221)",
    eta: "18 min",
    fee: "$0 delivery fee",
    distance: "0.5 mi",
    promo: "Spend $15, save $5",
    categoryIds: ["all", "mexican", "offers"],
  },
  {
    id: "5",
    name: "Crispy Bird",
    image: img("restaurant-chicken.jpg"),
    cuisine: "Chicken • Fast Casual",
    rating: 4.5,
    ratingsCount: "(980)",
    eta: "20 min",
    fee: "$2.49 delivery fee",
    distance: "1.1 mi",
    categoryIds: ["all", "burgers"],
  },
  {
    id: "6",
    name: "Fog City Ramen",
    image: img("restaurant-ramen.jpg"),
    cuisine: "Ramen • Japanese",
    rating: 4.8,
    ratingsCount: "(2,774)",
    eta: "32 min",
    fee: "$0 delivery fee",
    distance: "1.9 mi",
    dashpass: true,
    categoryIds: ["all", "asian"],
  },
  {
    id: "7",
    name: "Garden Bowl",
    image: img("restaurant-salad.jpg"),
    cuisine: "Salads • Healthy",
    rating: 4.4,
    ratingsCount: "(612)",
    eta: "16 min",
    fee: "$0 delivery fee",
    distance: "0.4 mi",
    dashpass: true,
    categoryIds: ["all", "healthy", "pickup"],
  },
  {
    id: "8",
    name: "Nonna's Pasta House",
    image: img("restaurant-pasta.jpg"),
    cuisine: "Italian • Pasta",
    rating: 4.7,
    ratingsCount: "(1,208)",
    eta: "30 min",
    fee: "$1.49 delivery fee",
    distance: "1.4 mi",
    categoryIds: ["all", "pizza"],
  },
  {
    id: "9",
    name: "Embarcadero Coffee",
    image: img("restaurant-coffee.jpg"),
    cuisine: "Cafe • Coffee",
    rating: 4.6,
    ratingsCount: "(890)",
    eta: "12 min",
    fee: "$0 delivery fee",
    distance: "0.3 mi",
    categoryIds: ["all", "coffee", "pickup"],
  },
  {
    id: "10",
    name: "Sweet Battery",
    image: img("restaurant-dessert.jpg"),
    cuisine: "Dessert • Bakery",
    rating: 4.8,
    ratingsCount: "(1,102)",
    eta: "24 min",
    fee: "$0 delivery fee",
    distance: "0.9 mi",
    dashpass: true,
    promo: "20% off select desserts",
    categoryIds: ["all", "dessert", "offers"],
  },
  {
    id: "11",
    name: "Ferry Building Deli",
    image: img("restaurant-sandwich.jpg"),
    cuisine: "Sandwiches • Deli",
    rating: 4.5,
    ratingsCount: "(744)",
    eta: "15 min",
    fee: "$0 delivery fee",
    distance: "0.2 mi",
    categoryIds: ["all", "pickup", "healthy"],
  },
  {
    id: "12",
    name: "Lotus Thai Kitchen",
    image: img("restaurant-thai.jpg"),
    cuisine: "Thai • Asian",
    rating: 4.7,
    ratingsCount: "(2,331)",
    eta: "26 min",
    fee: "$1.99 delivery fee",
    distance: "1.3 mi",
    dashpass: true,
    categoryIds: ["all", "asian"],
  },
];

export const footerColumns = {
  knowUs: [
    "About Us",
    "Careers",
    "Investors",
    "Company Blog",
    "Engineering Blog",
    "Merchant Blog",
    "Gift Cards",
    "Promotions",
    "Dasher Central",
    "LinkedIn",
    "Glassdoor",
    "Accessibility",
    "Newsroom",
  ],
  help: ["Account Details", "Order History", "Help"],
  business: [
    "Become a Dasher",
    "YemekYol Merchant",
    "Get Dashers for Deliveries",
    "Get YemekYol for Business",
  ],
};
